name: Build

# Controls when the workflow will run
on:
  push:
# pull_request:

  workflow_dispatch:

jobs:
  vpm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Remove unused files
        run: rm -rf Tests Tests.meta
      - name: Make zip
        run: zip -r $(jq -r '.name' package.json)-$(jq -r '.version' package.json).zip $(ls)
      - uses: actions/upload-artifact@v3
        with:
          name: vpm
          path: "*.zip"

  release:
    if: startsWith(github.ref, 'refs/tags/')
    needs: [vpm]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@v3
        with:
          name: vpm

      - uses: softprops/action-gh-release@v1
        with:
          files: |
            package.json
            *.zip
